language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script: python sync.py
deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: build/
  target-branch: master
  on:
    branch: build
before_install:
- echo $GPG_KEY | gpg --passphrase-fd 0 service-account.json.gpg
