language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt

script:
  python sync.py

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as an environment variable
    keep-history: true
    local-dir: build/
    target-branch: master
    on:
      branch: build
